# 工作流程的名字
name: Release jar

# 工作流程觸發的時機，這裡是當一個版本標籤推送到倉庫時觸發
on:
  push:
    tags:
      - "v*"

# 這個工作流程需要執行的任務
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 這個任務的步驟
    steps:
      # 拉取項目代碼
      - uses: actions/checkout@v2.2.0
      # 建立 Java 環境
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: "1.8"
      # 建立 Maven 環境
      - name: Setup Maven
        uses: aahmed-se/setup-maven@v3
        with:
          maven-version: 3.6.3
      # 檢查版本
      #      - run: javac -version
      #      - run: java -version
      #      - run: mvn --version
      # 打包 Jar
      - run: mvn clean package
      - run: cp /home/runner/work/UpdaterLab/UpdaterLab/target/UpdaterLab-1.0-SNAPSHOT.jar /home/runner/work/UpdaterLab/UpdaterLab/target/UpdaterLab.jar
      # 發佈到 Release
      - name: Release jar
        uses: ncipollo/release-action@v1.7.1
        with:
          artifacts: "/home/runner/work/UpdaterLab/UpdaterLab/target/UpdaterLab.jar"
          token: ${{ secrets.RELEASE_TOKEN }}